version: '3.8'

services:
  ollama:
    build: ./ollama
    image: skandarchahbouni/ollama 
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: "curl -f http://localhost:11434"
      interval: 30s
      timeout: 5s
      retries: 3

  vectordb:
    build: ./vectordb
    image: skandarchahbouni/vectordb
    ports:
      - "8000:8000"
    volumes:
      - vectordb-stores:/app/vectordb-stores
    healthcheck:
      test: "curl -f http://localhost:8000/docs"
      interval: 30s
      timeout: 5s
      retries: 3
  
  information_retrieval:
    build: ./information_retrieval
    image: skandarchahbouni/information_retrieval
    ports:
      - "5000:5000"
    healthcheck:
      test: "curl -f http://localhost:5000/docs"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      ollama:
        condition: service_healthy
      vectordb:
        condition: service_healthy
  
  response_generator:
    build: ./response_generator
    image: skandarchahbouni/response_generator
    ports:
      - "5001:5001"
    healthcheck:
      test: "curl -f http://localhost:5001/docs"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      ollama:
        condition: service_healthy

  query_manager:
    build: ./query_manager
    image: skandarchahbouni/query_manager
    ports:
      - "5002:5002"
    healthcheck:
      test: "curl -f http://localhost:5002/docs"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      information_retrieval:
        condition: service_healthy
      response_generator:
        condition: service_healthy
  
  gui:
    build: ./gui
    image: skandarchahbouni/gui
    ports:
      - "4000:4000"
    depends_on:
      query_manager: 
        condition: service_healthy

volumes:
  ollama:
  vectordb-stores: