apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
        - name: gui
          image: youssef07/rag-gui
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: gui
spec:
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
