apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-manager
  template:
    metadata:
      labels:
        app: query-manager
    spec:
      containers:
        - name: query-manager
          image: youssef07/rag-query_manager
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /docs
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: query-manager
spec:
  selector:
    app: query-manager
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
