apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: response-generator
  template:
    metadata:
      labels:
        app: response-generator
    spec:
      containers:
        - name: response-generator
          image: youssef07/rag-response_generator
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /docs
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: response-generator
spec:
  selector:
    app: response-generator
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
