apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectordb
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
        - name: vectordb
          image: youssef07/rag-vectordb
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app/vectordb-stores
              name: vectordb-volume
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: vectordb-volume
          persistentVolumeClaim:
            claimName: vectordb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vectordb
spec:
  selector:
    app: vectordb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
