FROM ollama/ollama
RUN apt-get update && apt-get install -y curl
RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull gemma:2b
RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull nomic-embed-text